resources:
- node/overlays/featureenv/region
namespace: fe-FEATURE_ENV_NAME
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: node-image-placeholder
  newName: mikogs/project-template-node
  newTag: d99f1ae
